### ISSUE TITLE
RuntimeError: The size of tensor a (130528) must match the size of tensor b (4096) at non-singleton dimension 2

### ISSUE THREAD

**Issue by cweihua** [michael-wzhu/PromptCBLUE#11]
Traceback (most recent call last):
  File "D:\PycharmProjects\CBLUE-main\baselines\run_cdn.py", line 222, in <module>
    main()
  File "D:\PycharmProjects\CBLUE-main\baselines\run_cdn.py", line 149, in main
    global_step, best_step = trainer.train()
  File "D:\PycharmProjects\CBLUE-main\.\cblue\trainer\train.py", line 87, in train
    loss = self.training_step(model, item)
  File "D:\PycharmProjects\CBLUE-main\.\cblue\trainer\train.py", line 1769, in training_step
    outputs = model(labels=labels, **inputs)
  File "D:\PycharmProjects\CBLUE-main\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\PycharmProjects\CBLUE-main\.\cblue\models\model.py", line 119, in forward
    avg_hidden_states = torch.mean((last_hidden_states + first_hidden_states), dim=1)
RuntimeError: The size of tensor a (130528) must match the size of tensor b (4096) at non-singleton dimension 2
我在原程序上做了一些修改，遇见了一些问题，我debug了一下发现是last_hidden_states和first_hidden_states的第三维不匹配，前者是130528，后者是4096，请问应该怎么处理

**Comment by michael-wzhu** [comment]
130528看起来是词汇表大小？4096是模型hidden size，最直接的处理是这两个不能相加

**Comment by cweihua** [comment]
> 

谢谢，找到问题所在了，你说的是对的

**Comment by cweihua** [comment]
> 130528看起来是词汇表大小？4096是模型hidden size，最直接的处理是这两个不能相加

谢谢，你说的是对的，解决问题了
