### ISSUE TITLE
vocab_file is not None

### ISSUE THREAD

**Issue by liuxiaohao-xn** [michael-wzhu/PromptCBLUE#15]
运行时候报如下错误：
```python
Traceback (most recent call last):
  File "src/ft_chatglm_lora/main.py", line 500, in <module>
    main()
  File "src/ft_chatglm_lora/main.py", line 125, in main
    tokenizer = ChatGLMTokenizer.from_pretrained(
  File "/asr_lu/user/liuxiaohao/application/miniconda3/envs/ddp/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 1811, in from_pretrained
    return cls._from_pretrained(
  File "/asr_lu/user/liuxiaohao/application/miniconda3/envs/ddp/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 1965, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "/asr_lu/user/liuxiaohao/project/challenges/PromptCBLUE/src/ft_chatglm_ptuning/tokenization_chatglm.py", line 209, in __init__
    self.sp_tokenizer = SPTokenizer(vocab_file, num_image_tokens=num_image_tokens)
  File "/asr_lu/user/liuxiaohao/project/challenges/PromptCBLUE/src/ft_chatglm_ptuning/tokenization_chatglm.py", line 55, in __init__
    assert vocab_file is not None
AssertionError
```
我从hf上下载的chatglm2权重，里面并没有发现vocab_file文件
```text
-rw-rw-rw-. 1 root root       1223 Jul 24 09:34 config.json
-rw-r--r--. 1 root root        200 Jul 25 02:07 configuration.json
-rw-rw-rw-. 1 root root       2246 Jul 24 09:34 configuration_chatglm.py
-rw-rw-rw-. 1 root root      50717 Jul 24 09:34 modeling_chatglm.py
-rw-rw-rw-. 1 root root 1827780615 Jul 24 10:05 pytorch_model-00001-of-00007.bin
-rw-rw-rw-. 1 root root 1968299005 Jul 24 10:29 pytorch_model-00002-of-00007.bin
-rw-rw-rw-. 1 root root 1927414561 Jul 24 10:52 pytorch_model-00003-of-00007.bin
-rw-rw-rw-. 1 root root 1815225523 Jul 24 11:15 pytorch_model-00004-of-00007.bin
-rw-rw-rw-. 1 root root 1968299069 Jul 24 11:41 pytorch_model-00005-of-00007.bin
-rw-rw-rw-. 1 root root 1927414561 Jul 24 12:05 pytorch_model-00006-of-00007.bin
-rw-rw-rw-. 1 root root 1052808067 Jul 24 12:19 pytorch_model-00007-of-00007.bin
-rw-rw-rw-. 1 root root      20438 Jul 24 12:19 pytorch_model.bin.index.json
-rw-rw-rw-. 1 root root      14692 Jul 24 12:19 quantization.py
-rw-rw-rw-. 1 root root      10061 Jul 24 12:19 tokenization_chatglm.py
-rw-rw-rw-. 1 root root    1018370 Jul 24 12:19 tokenizer.model
-rw-rw-rw-. 1 root root        244 Jul 24 12:19 tokenizer_config.json
```

**Comment by waterStudy** [comment]
缺少了ice_text.model文件

**Comment by YINhang23** [comment]
> 缺少了ice_text.model文件

那这个是要下载么？从哪里下载？还是说要自己写？

**Comment by michael-wzhu** [comment]
the current code does not work with ChatGLM-2.
